src/Entity/Enchere.php
<?php

namespace App\Entity;

use App\Repository\EnchereRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnchereRepository::class)]
class Enchere
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    private $date_debut;

    #[ORM\Column(type: 'datetime')]
    private $date_fin;

    #[ORM\Column(type: 'integer')]
    private $id_panier_globale;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getEnchereFournisseurs(): Collection
    {
        return $this->enchereFournisseurs;
    }

    public function addEnchereFournisseur(EnchereFournisseur $enchereFournisseur): self
    {
        if (!$this->enchereFournisseurs->contains($enchereFournisseur)) {
            $this->enchereFournisseurs[] = $enchereFournisseur;
            $enchereFournisseur->setIdEnchere($this);
        }

        return $this;
    }

    public function removeEnchereFournisseur(EnchereFournisseur $enchereFournisseur): self
    {
        if ($this->enchereFournisseurs->removeElement($enchereFournisseur)) {
            // set the owning side to null (unless already changed)
            if ($enchereFournisseur->getIdEnchere() === $this) {
                $enchereFournisseur->setIdEnchere(null);
            }
        }

        return $this;
    }

    public function getIdPanierGlobale(): ?int
    {
        return $this->id_panier_globale;
    }

    public function setIdPanierGlobale(int $id_panier_globale): self
    {
        $this->id_panier_globale = $id_panier_globale;

        return $this;
    }
}

src/Controller/EnchereController.php
<?php

namespace App\Controller;

use App\Entity\EnchereFournisseur;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Enchere;
use App\Form\AddEnchereType;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\EnchereRepository;

class EnchereController extends AbstractController
{

    #[Route(path: '/enchere', name: 'app_enchere')]
    public function index(EnchereRepository $enchereRepo): Response
    {
        $this->denyAccessUnlessGranted(attribute: 'IS_AUTHENTICATED_FULLY'); //verif auth

        $client = HttpClient::create(defaultOptions: ['verify_peer' => false, 'verify_host' => false]); //creation clien qui peut faire des requettes vers l'api sans verif certif ssl
        $res  = $client->request(method: 'GET', url: 'https://localhost:44335/Fournisseurs/AllFournisseurs');

        $allfournisseur = $res->toArray();

        date_default_timezone_set('Europe/Paris');
        $dateactuelle = date('d-M-y  H:i');

        $user = $this->getUser();//recup du nom d'user

        $societe=null;
        foreach ( $allfournisseur as $fournisseur)// relation entre user symfony et le fournisseur
        {
            if ($fournisseur['email'] == strval(value: $user->getUserIdentifier() )){
                $societe_Fournisseur = $fournisseur['societe'];
                $Id_fournisseur = $fournisseur['id'];
            }
            if (strval(value: $user->getUserIdentifier()) == 'enzo')
            {
                $societe_Fournisseur = (strval(value: $user->getUserIdentifier()));
                $Id_fournisseur = 0;
            }
        }
        if ($societe_Fournisseur===null) // si le user ne correspond à aucun fournisseur alors on revient sur la page de base
        {
            return $this->redirectToRoute(route: 'app_page');
        }

        //recuperation du panier global
        $res2 = $client->request(method: 'GET', url: 'https://localhost:44335/Panier_Global/AllPanierGlobal');
        $allpanierglobal= $res2 ->toArray();
        $dernierPanierGlobal = end(array: $allpanierglobal);

        $derniereenchere = $enchereRepo->findOneBy([], ['id' => 'DESC']);



        $res4 = $client->request(method: 'GET', url: 'https://localhost:44335/Panier_Global_Details/GetGlobalDetailByPanier?ID='.$dernierPanierGlobal['id'].''); //appel a l'api
        $panierglobaldetail = $res4->toArray();


        $res5 = $client->request(method: 'GET', url: 'https://localhost:44335/Reference/AllReference'); //appel a l'api
        $AllReferences = $res5->toArray();

        $req6 = $client->request(method: 'GET', url: 'https://localhost:44335/Fournisseur_Reference/GetFournisseurReferenceByFournisseur?ID=1');
        $referenceDuFournisseur = $req6->toArray();

        $referenceFiltres = [];

        foreach ($referenceDuFournisseur as $referenceFournisseurTmp) {
            foreach ($AllReferences as $referenceTmp) {
                if ($referenceFournisseurTmp["id_references"] == $referenceTmp["id"]) {
                    array_push($referenceFiltres, $referenceTmp);
                }
            }
        }

        dump($derniereenchere);






            return $this->render(view: 'enchere/index.html.twig', parameters: [
            'controller_name' => 'EnchereController',
            // test de connection a l'api   'status' => strval($res->getStatusCode()),// creer un parametre status converti en string pour affichage en html
            'allfournisseur' => $allfournisseur,
            'idfournisseur' => $Id_fournisseur,
            /*'refbypanier' => $refbypanier,*/
            'panierglobaldetail' => $panierglobaldetail,
            'societe_Fournisseur' => $societe_Fournisseur,
            'encheres' => $derniereenchere,
            'enchere' => $enchereRepo ->findAll(),
            'dateactuelle' => $dateactuelle,
            'AllReferences' => $referenceFiltres
        ]);
    }

    #[Route(path: '/enchere/ajouter_enchere', name: 'ajouter_enchere')]
    public function AjouterEnchere(\Symfony\Component\HttpFoundation\Request $request,EntityManagerInterface $entityManager,EnchereRepository $enchereRepo): Response
    {

        $this->denyAccessUnlessGranted(attribute: 'IS_AUTHENTICATED_FULLY'); //verif auth

        $user = $this->getUser();
        if (strval(value: $user->getUserIdentifier()) != 'mauris@mauris.com')
        {
            return $this->redirectToRoute(route: 'app_page');
        }
        $client = HttpClient::create(defaultOptions: ['verify_peer' => false, 'verify_host' => false]); //creation clien qui peut faire des requettes vers l'api sans verif certif ssl
        //recuperation du panier global
        $res2 = $client->request(method: 'GET', url: 'https://localhost:44335/Panier_Global/AllPanierGlobal');
        $allpanierglobal= $res2 ->toArray();
        $dernierPanierGlobal = end(array: $allpanierglobal);
        date_default_timezone_set('Europe/Paris');
        $semaineactuelle = date('W');
        $derniereenchere = $enchereRepo->findOneBy([], ['id' => 'DESC']);


        $enchere = new Enchere();
        $form = $this->createForm(type: AddEnchereType::class, data: $enchere);
        $form->handleRequest(request: $request);

        if ($form->isSubmitted() && $form->isValid()) {
            $enchere = $form->getData();

            $entityManager->persist(entity: $enchere);
            $entityManager->flush();

            return $this->redirectToRoute(route: 'app_enchere');
        }
        return $this->render(view: 'enchere/ajouter_enchere.html.twig', parameters: [

            'allpanierglobal' => $allpanierglobal,
            'dernierPanierGlobal' => $dernierPanierGlobal,
            'form' => $form->createView(),
            'semaineactuelle' => $semaineactuelle,
            'derniereenchere' => $derniereenchere,
        ]);

    }

    #[Route(path: '/encherir', name: 'encherir')]
    public function encherir(Request $request, EntityManagerInterface $entityManager,EnchereRepository $enchereRepo) {
        $parameters = json_decode($request->getContent(), true);
        $user = $this->getUser();
        $fournisseur = strval(value: $user->getUserIdentifier());

        //$derniereenchere = $enchereRepo->findOneBy([], ['id' => 'DESC']);


        $enchereFournisseur=new EnchereFournisseur();
        $enchereFournisseur->setIdEnchereId($parameters['id_enchere']);
        $enchereFournisseur->setPrix($parameters['prix']);
        $enchereFournisseur->setFournisseur($fournisseur) ;
        $enchereFournisseur->setProduit($parameters['reference']);
        $enchereFournisseur->setIdPanierglobaldetail($parameters['idpanierglobal']);

        $entityManager->persist($enchereFournisseur);
        $entityManager->flush();

        $client = HttpClient::create(defaultOptions: ['verify_peer' => false, 'verify_host' => false]);
        $res  = $client->request(method: 'GET', url: 'https://localhost:44335/Fournisseurs/AllFournisseurs');
        $allfournisseur = $res->toArray();



        /*foreach ( $allfournisseur as $fournisseur)// relation entre user symfony et le fournisseur
        {
            if ($fournisseur['email'] == strval(value: $user->getUserIdentifier())) {

                $Id_fournisseur = $fournisseur['id'];
            }
        }

        $client->request( 'POST',  'https://localhost:44335/Panier_Fournisseurs',
            ['body' => [
                "id_fournisseurs"=>$Id_fournisseur,
                "puht"=>$parameters['prix'],
                "id_panier_global_detail"=>$parameters['idpanierglobal'],

            ]]);*/
////
//
//         $client->request( 'POST',  'https://localhost:44362/OffreFournisseur',
//            ['headers' => [
//                  "iD_FOURNISSEURS"=>$Id_fournisseur,
//                "offres"=>$parameters['prix'],
//                "iD_PANIER_GLOBALS_DETAILS"=>$parameters['idpanierglobaledetails'],
//
//                ]]);



        return new JsonResponse(array('name' => $parameters['prix']));
    }

}

templates/enchere/ajouter_enchere.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Enchere{% endblock %}

{% block body %}

    {{ include('navbar/navbar.html.twig')}}

    <h1>Ajouter une Enchere</h1>
    <div class="container">


        <p>semaine actuelle: {{ semaineactuelle+1 }}</p>
        <p>semaine du dernier panier globale: {{ dernierPanierGlobal.semaine }}</p>
        <p>id du dernier panier globale: {{ dernierPanierGlobal.id }}</p>

        {% if dernierPanierGlobal.semaine != semaineactuelle+1 %}
            <h3> ATTENTION !!! il n'existe pas de panier global pour cette semaine </h3>
        {% else %}
           {# {% if dernierPanierGlobal.id == derniereenchere.id_panier_globale %}
                <h3> ATTENTION !!! il existe deja une enchere pour cette semaine </h3>
            {% else %} #}
                <h3> Il n'y a pas d'enchere pour cette semaine </h3>
{#            {% endif %}#}
        {% endif %}




        <div class="form-group">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-success">Ajouter</button>
            {{ form_end(form) }}
        </div>
    </div>

    </ul>

{% endblock %}

templates/enchere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}enchere{% endblock %}

{% block body %}

    {{ include('navbar/navbar.html.twig')}}

    <h1 class="text-center">Enchere </h1>
    <ul>
        {% if (dateactuelle |date('d-M-y  H:i') < encheres.dateDebut |date('d-M-y  H:i')) %}
            <a>il n'y a pas encore d'enchere pour cette semaine </a>
        {% endif %}
        {% if (encheres.dateFin |date('d-M-y  H:i') < dateactuelle |date('d-M-y  H:i')) %}
            <a>enchere est deja passée pour cette semaine </a>
        {% endif %}
        {% if ( encheres.dateDebut |date('d-M-y  H:i') < dateactuelle |date('d-M-y  H:i') and  dateactuelle < encheres.dateFin |date('d-M-y  H:i')) %}

            <h3>l'enchere commencera le {{ encheres.dateDebut |date('d-M-y H:i:s')}} et ce finira le {{ encheres.dateFin |date('d-M-y H:i:s')}}</h3>
            <h3>vous encherissez pour la societé {{ societe_Fournisseur }}</h3>


            <table>
                <thead>
                <tr>
                    <td>Reférence</td>
                    <td>Marque</td>
                    <td>Libellé</td>
                    <td>Enchère</td>
                </tr>
                </thead>
                <tbody>
                {% for AllReference in AllReferences %}
                    <tr>
                        <td>{{ AllReference.reference }}</td>
                        <td>{{ AllReference.marque }}</td>
                        <td>{{ AllReference.libelle }}</td>


                        <td><input class="{{ AllReference.reference }}" type="number" min="0"></td>
                        <td><button type="submit" class="btn btn-success" onclick="faireUneEnchere('{{ AllReference.reference }}'), alert('vous avez enchérie')" >Enchérir</button></td>

                    </tr>
                {% endfor %}

                </tbody>
            </table>

        {% endif %}

        {% block javascripts %}
            <script type="text/javascript">
                const faireUneEnchere = (reference) => {
                    var prix = document.getElementsByClassName(reference)[0].value
                    var idenchere = {{ encheres.id }}
                    var panierglobalid = {{ encheres.IdPanierGlobale}}
                    console.log('Prix: ' + prix + ' reference :' + reference + 'id enchere :' + idenchere + 'panier global : ' + panierglobalid)
                    let xhr = new XMLHttpRequest();
                    xhr.open("POST", "/encherir");
                    xhr.send(JSON.stringify({ "reference": reference, "prix": prix, "id_enchere": idenchere, "idpanierglobal": panierglobalid }));
                }
            </script>

        {% endblock %}



    </ul>

{% endblock %}